---
- name: Restart apache on ubuntu
  ansible.builtin.service:
    name: apache2
    state: restarted
  listen: restart web server
  when: ansible_distribution == "Ubuntu"

- name: Restart httpd on centos
  ansible.builtin.service:
    name: httpd
    state: restarted
  listen: restart web server
  when: ansible_distribution == "CentOS"

- name: Restart Nagios
  ansible.builtin.service:
    name: nagios
    state:  restarted
  listen: restart nagios